CREATE TABLE Users (
  Id INT PRIMARY KEY IDENTITY(1, 1),
  Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Orders (
  Id INT PRIMARY KEY IDENTITY(1, 1),
  UserId INT NOT NULL,
  OrderDate DATETIME NOT NULL,
  TotalAmount DECIMAL(10, 2) NOT NULL,
  Status NVARCHAR(50) NOT NULL,
  FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE OrderItems (
  Id INT PRIMARY KEY IDENTITY(1, 1),
  OrderId INT NOT NULL,
  ProductName NVARCHAR(100) NOT NULL,
  Quantity INT NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);